### ISSUE TITLE
Commit package.json and remove node_modules

### ISSUE THREAD

**Issue by chrmod** [travelingwizard/steps#1]
So that the electron app can be build on any operating system.

**Comment by travelingwizard** [comment]
I use a my Linux machine to build rpm, deb, linux zip and Mac. I use a Windows Virtual Machine to build the windows version. Though the use of wine I should be able to build the windows version too, but as of yet it's continued to fail and the only answers I've found is "install wine". Because this is done in my free time for a free application, I haven't committed the effort into figuring  it out. 

From Windows, I don't think it's possible to build anything but the windows version. It might be possible but Fedora is my primary OS and my comfort zone.

**Comment by chrmod** [comment]
Hi @travelingwizard - I have some experience in running multiplatform builds on CI. Nowadays it should be possible to use Github actions to make builds for all platform. If you like I can help.

**Comment by travelingwizard** [comment]
I had similar thoughts. 

I use electron forge to help automate the building of the application locally. I don't have my build files in any particular repo yet because I wanted to make sure Steps had a way to receive contributors. If it's helpful I will put together another repository that has my build configs in it for electron forge.

**Comment by chrmod** [comment]
I saw some of the electron-forge configs on `master` branch. That's what I've copied over to #2. If there is something else please let me know, I'm happy to put all those things together and setup automation.
